name: Biblist Verification
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
  workflow_call:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          extract: true
          repository: "AliaumeL/bibadac"
      - name: Allow execution
        run: |
          chmod +x bibadac
      - name: Run bibadac
        run: |
          ./bibadac check *.bib



