name: Biblist Verification
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
  workflow_call:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fetch bibadac
        run: |
          curl "https://github.com/AliaumeL/bibadac/releases/download/v.0.0.1/bibadac-x86_64-unknown-linux-gnu.tar.gz" -o bibadac.tar.gz
          tar -xzf bibadac.tar.gz
          chmod +x bibadac
      - name: Run bibadac
        run: |
          bibadac check *.bib



